### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [erskin19/TC359RubyForms#1]
One of the few projects I haven't been able to immediately break! While it does work though, I would add a `required` attribute to all of these fields to so that someone doesn't enter a year and wonder why nothing is showing up. I also see [a single tab character](https://github.com/erskin19/TC359RubyForms/blob/master/app.rb#L8) hanging out in `app.rb`. You should be able to use [this resource](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to fix it.

Let me know when those two changes are made and I'll take another look.

**Comment by erskin19** [comment]
Hi Chris, I believe I have implemented these two changes.

**Comment by chrisvfritz** [comment]
:+1: Much better!
